apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf 
  namespace: gitlab 
data:
  nginx.conf: |-
    error_log stderr notice;

    worker_processes auto;
    events {
      multi_accept on;
      use epoll;
      worker_connections 1024;
    }

    stream {
        upstream kube_apiserver {
            least_conn;
            server 192.168.100.161:6443;
            server 192.168.100.162:6443;
            server 192.168.100.163:6443;
        }

        server {
            listen        0.0.0.0:6443;
            proxy_pass    kube_apiserver;
            proxy_timeout 10m;
            proxy_connect_timeout 1s;
        }
    }
